### GET request that fetches all the hotels
GET http://localhost:8080/hotels
Content-Type: application/json

### GET request that fetches hotels by name
GET http://localhost:8080/hotels/Ibis
Content-Type: application/json

### POST request to checkin new client
POST http://localhost:8080/hotels/Continental/checkout
Content-Type: application/json

{
  "id": 6,
  "firstName": "John",
  "lastName": "Doe"
}

### POST request to create new hotel
POST http://localhost:8080/hotels
Content-Type: application/json

{
  "name": "Palermo",
  "classification": 4,
  "nbRooms": 60
}

### PUT request to change hotel
PUT http://localhost:8080/hotels/Ibis
Content-Type: application/json

{
  "name": "Ibis",
  "classification": 3,
  "nbRooms": 30
}

### DELETE request to delete hotel
DELETE http://localhost:8080/hotels/Ibis
Content-Type: application/json

### GET request that fetches all the clients
GET http://localhost:8080/clients
Content-Type: application/json

### POST request to create new client
POST http://localhost:8080/clients
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe"
}

###